name: Create Release Promotion Pull Request

on:
  push:
    branches:
      - 'release/*'

jobs:
  releasePromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo GITHUB_REF_NAME test
        run: echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create pull request
        run: gh pr create -B main -H ${GITHUB_REF_NAME} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}