name: Create Release Promotion Pull Request

on:
  push:
    branches:
      - 'release/*'

jobs:
  releasePromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the pushed branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Create Pull Request from Pushed Branch to Main
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: ${GITHUB_REF_NAME}
          commit-message: Promote ${GITHUB_REF_NAME} to main branch
          title: "PR for ${GITHUB_REF_NAME}"
          body: "This PR promotes the release branch ${GITHUB_REF_NAME} to main."
          token: ${{ secrets.GITHUB_TOKEN }}