name: Create Release Promotion Pull Request

on:
  push:
    branches:
      - 'release/*'

jobs:
  releasePromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B main -H ${GITHUB_REF_NAME} --title 'Update release files for ${VERSION}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}